### ISSUE TITLE
Bind the event with sync modifier compile fail.

### ISSUE THREAD

**Issue by yeyuqiudeng** [vuejs/babel-plugin-transform-vue-jsx#109]
Here is my code:

```
render () {
    return <el-dialog
        title={this.formTitle}
        size={this.editor.size}
        visible={this.showForm}
        onUpdate:visible={val => this.showForm = val}
    >
    </el-dialog>
  }
```

But compile fail.

Here is the error message: 

```
Syntax Error: Namespaced tags/attributes are not supported. JSX is not XML.
For attributes like xlink:href, use xlinkHref instead.

  66 |         size={this.editor.size}
  67 |         visible={this.showForm}
> 68 |         onUpdate:visible={val => this.showForm = val}
     |         ^
  69 |     >
```

I had ask this question in forum, here is the link [Use jsx to write vue component，How to bind the event with sync modifier？](https://forum.vuejs.org/t/use-jsx-to-write-vue-component-how-to-bind-the-event-with-sync-modifier/22681)

**Comment by nickmessing** [comment]
Unfortunately you cannot use colon in event names in JSX because that is reserved for XML namespacing. That is a limitation of JSX specification itself and there is no good way around that. Unfortunately you have to change event names to have no colons, switch to vue templates or write render function in plain javascript to avoid that.

P.S. Actually there is another way, you can spread events like this:
```js
render () {
  const toSpread = {
    on: {
      'update:visible' (val) {
        this.showForm = val
      }
    }
  }
  return <el-dialog {...toSpread} />
}
```

**Comment by njleonzhang** [comment]
@yeyuqiudeng try https://github.com/njleonzhang/babel-plugin-vue-jsx-sync
