### ISSUE TITLE
h auto inject not working in 3.5.0

### ISSUE THREAD

**Issue by andtii** [vuejs/babel-plugin-transform-vue-jsx#111]
Hey, i have an issue with the h auto inject not working in 3.5.0 when i add back the render(h) everything works again. Im using .tsx and config in webpack like this.

![image](https://user-images.githubusercontent.com/1434571/33727131-75d609aa-db77-11e7-80da-fa8aa327e102.png)

Code like this
![image](https://user-images.githubusercontent.com/1434571/33727046-3598000a-db77-11e7-8786-969a2980feae.png)

And .babelrc is like this
![image](https://user-images.githubusercontent.com/1434571/33727070-49adde7a-db77-11e7-9dc2-b6d8c35ae71d.png)

packages used is
![image](https://user-images.githubusercontent.com/1434571/33727192-9e3d8b98-db77-11e7-88c3-72939f07fcf3.png)

the transpiling seems to be working except for h auto inject when i remove the h i get this error 

![image](https://user-images.githubusercontent.com/1434571/33727240-bc680684-db77-11e7-972b-998fb6fd9ac9.png)

**Comment by Foolyou** [comment]
Set `target` in your tsconfig to 'es2015' should solve this problem, as the document says:

===
Starting with version 3.4.0 we automatically inject const h = this.$createElement in any method and getter (not functions or arrow functions) declared in <strong>ES2015 syntax</strong> that has JSX so you can drop the (h) parameter.
===

**Comment by nickmessing** [comment]
@andtii, in order to get h automatically injected you need to have es2015 going through babel. If you are using typescript I guess typescript transpiles es2015 methods and getters to es5.1 and that is what breaks it. That is something that babel should do, and not typescript compiler. You should just configure typescript to output to es2015 instead and then let babel handle it from there.
