### ISSUE TITLE
how to use v-model in jsx expression?

### ISSUE THREAD

**Issue by wuchuguang** [vuejs/babel-plugin-transform-vue-jsx#27]
```
<input v-model="data1" />
data(){
   return {
       data1: ''
   };
}

```

how to write jsx .
i try to use 
`h('input',{directives:[{name:'v-model',value:'data1'}]})`

not report error .
thx.

**Comment by sqal** [comment]
@wuchuguang you can't use built-in directives inside render function (except v-show or custom directives). In order to recreate v-model in render function you have to bind input/change event to the input field and then take input's value from event object and update your model data. It should look like this:

```
methods: {
  onInput(e) {
    this.data1 = e.target.value;
  },
},
render(h) {
  return (
    <input on-input={this.onInput} />
  )
}
```

**Comment by yyx990803** [comment]
^ what @sqal suggested

**Comment by nickmessing** [comment]
@wuchuguang, now you can use `v-model` in JSX if you add my [v-model](https://github.com/nickmessing/babel-plugin-jsx-v-model) transform.
