### ISSUE TITLE
Change 'identifier' to 'this.$createElement'

### ISSUE THREAD

**Issue by QingWei-Li** [vuejs/babel-plugin-transform-vue-jsx#55]
I noticed that render function is called by the current vm (See [vue.runtime.common.js#L2216](https://github.com/vuejs/vue/blob/dev/dist/vue.runtime.common.js#L2216)). Maybe we can replace `h` to `this.$createElement`? We can remove "ugly" `h`.

I can submit PR if you agree.

**Comment by LinusBorg** [comment]
That's not a good idea, because it's such a long string. This will significantly increase the size of the generated code.

**Comment by nickmessing** [comment]
@LinusBorg, @yyx990803, is it possible to at least add a configuration for that so that we can use something like [this](https://forum.vuejs.org/t/hiddent-potential-optimisation-why-there-are-no-docs-for-that/7530) without workarounds like `const h = this.$createElement`, something like react's comment `//@jsx this.$createElement` in the files where we use that.

**Comment by yyx990803** [comment]
@nickmessing that sounds reasonable - open to a PR

**Comment by nickmessing** [comment]
can you take a look at [this PR](https://github.com/vuejs/babel-plugin-transform-vue-jsx/pull/58)? As a workaround I removed the es2015 preset temporarily but there should be a way to make it work with the preset.

**Comment by QingWei-Li** [comment]
Thank @nickmessing
